--Eduardo Bezerra - RM: 98890
--Jefferson Mendes de Farias Lima - RM: 552052
--Joao Vitor Vicente Benjamin - RM: 98938
--Luiz Felipe Biazzola Cavalcante - RM: 99250
--Silas Henrique da Silva Oliveira - RM: 98965

--Drop Tabelas
DROP TABLE t_bc_profissional;
DROP TABLE t_bc_dados_vitais;
DROP TABLE t_bc_paciente;
DROP TABLE t_bc_contato;
DROP TABLE t_bc_plano_saude;
DROP TABLE t_bc_credencial;



--Sequences

CREATE SEQUENCE SEQ_CONTATO
START WITH 1
INCREMENT BY 1  
MINVALUE 1 
MAXVALUE 1000
NOCYCLE;
CREATE SEQUENCE SEQ_PLANO_SAUDE
START WITH 1
INCREMENT BY 1  
MINVALUE 1 
MAXVALUE 1000
NOCYCLE;
CREATE SEQUENCE SEQ_PACIENTE
START WITH 1
INCREMENT BY 1  
MINVALUE 1 
MAXVALUE 1000
NOCYCLE;
CREATE SEQUENCE SEQ_DADOSVITAIS
START WITH 1
INCREMENT BY 1  
MINVALUE 1 
MAXVALUE 1000
NOCYCLE;
CREATE SEQUENCE SEQ_PROFISSIONAL
START WITH 1
INCREMENT BY 1  
MINVALUE 1 
MAXVALUE 1000
NOCYCLE;
CREATE SEQUENCE SEQ_CREDENCIAL
START WITH 1
INCREMENT BY 1  
MINVALUE 1 
MAXVALUE 1000
NOCYCLE;

--Criacao de Tabelas
CREATE TABLE T_BC_PLANO_SAUDE(
id_plano_saude NUMERIC CONSTRAINT PK_T_BC_PLANO_SAUDE PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
nivel VARCHAR(20) NOT NULL
);

CREATE TABLE T_BC_CREDENCIAL(
id_credencial NUMERIC CONSTRAINT PK_T_BC_CREDENCIAL PRIMARY KEY,
usuario VARCHAR(20) NOT NULL,
senha VARCHAR(20) NOT NULL
);


CREATE TABLE T_BC_CONTATO(
id_contato NUMERIC CONSTRAINT PK_T_BC_CONTATO PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
telefone VARCHAR(20) NOT NULL,
email VARCHAR(50)
);

CREATE TABLE T_BC_PACIENTE(
id_paciente NUMERIC CONSTRAINT PK_T_BC_PACIENTE PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
idade NUMERIC(3) NOT NULL,
telefone VARCHAR(20) NOT NULL,
id_plano_saude NUMERIC NOT NULL,
id_contato NUMERIC NOT NULL,
id_credencial NUMERIC NOT NULL,
CONSTRAINT FK_T_BC_PACIENTE_T_BC_PLANO_SAUDE FOREIGN KEY(id_plano_saude) REFERENCES T_BC_PLANO_SAUDE(id_plano_saude),
CONSTRAINT FK_T_BC_PACIENTE_T_BC_CONTATO FOREIGN KEY(id_contato) REFERENCES T_BC_CONTATO(id_contato),
CONSTRAINT FK_T_BC_PACIENTE_T_BC_CREDENCIAL FOREIGN KEY(id_credencial) REFERENCES T_BC_CREDENCIAL(id_credencial)
);

CREATE TABLE T_BC_DADOS_VITAIS(
id_dados_vitais NUMERIC CONSTRAINT PK_T_BC_DADOS_VITAIS PRIMARY KEY,
data_hora TIMESTAMP NOT NULL,
pas NUMERIC,
pad NUMERIC,
nivel_glicemico decimal(5,2),
saturacao decimal(5,2),
id_paciente NUMERIC not null,
CONSTRAINT FK_T_BC_DADOS_VITAIS_T_BC_PACIENTE FOREIGN KEY(id_paciente) REFERENCES T_BC_PACIENTE(id_paciente)
);

CREATE TABLE T_BC_PROFISSIONAL(
id_profissional NUMERIC CONSTRAINT PK_T_BC_PROFISSIONAL PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
especializacao VARCHAR(20) NOT NULL, 
id_credencial NUMERIC NOT NULL,
CONSTRAINT FK_T_BC_PROFISSIONAL_T_BC_CREDENCIAL FOREIGN KEY(id_credencial) REFERENCES T_BC_CREDENCIAL(id_credencial)
);